### ISSUE TITLE
Ground Control 2 - server timeout when trying to join a match

### ISSUE THREAD

**Issue by Lasercar** [openspy/openspy-core#11]
People can start matches, send chat messages and stuff, but they can't actually join any matches - because the server just timeouts. 

Matches used to work in 2021, so why don't they work now? Because I can't figure out why.

**Comment by chc** [comment]
This issue should be resolved now, if not please reopen. Thanks and apologies for the delay in answering.

**Comment by Lasercar** [comment]
![screen0037](https://github.com/user-attachments/assets/8cd596de-6590-4ee0-bb3b-9788e2ddabd1)
I've been able to test two people and both times I still got the timeout issue.
I'll test again tomorrow with someone who is located closer, just in case it's related to ping or something.

**Comment by Lasercar** [comment]
I don't think I'm able open this issue again, so @chc could you reopen it?
