### ISSUE TITLE
[Request] Provide IRC or Matrix Channel 

### ISSUE THREAD

**Issue by gegoxaren** [openspy/openspy-core#18]
Greetings!
I was wondering ig there is any official/semi-official IRC or Matrix Channel.

I personally think that would be a good thing to have, to ask about things and see if others have problems, etc etc...

Right now it seems that all services on the openspy.net, and beta.openspy.net always time out, and wanted to know if it was just a me-issue.

Thank you in advance,
Gustav.

**Comment by devzspy** [comment]
We are using Discord for our communications, both devs and contributors.

https://discord.gg/RfbT6fzAWz
